### PR TITLE
Style/Hide past talks

### PR DESCRIPTION
**Pull request by joshpuetz**
This is an attempt to style/hide past talks. I've added a function that applies the style `codeland-schedule__event-past` to the `codeland-schdule__event` div once it's talk end time has passed. Also added a `See Previously Aired/See Less button at the top of the schedule that mirror the functionality of the `see all` button.

codeland_-_DEV_local__Community_👩💻👨💻

### CODE REVIEW

**Comment by joshpuetz** [comment]
Hey @lisasy: is this something you can work with?

**Comment by lisasy** [comment]
@joshpuetz This looks good to me. I'll pull this down and create the styling updates. I'll let you know when that's completed :)

**Comment by lisasy** [comment]
@joshpuetz 

Hi @joshpuetz, I've added a simple style change for past events, which is to dim the opacity.

Given that our team has been talking more about improving the way people can see past and future events (without being overwhelmed by the amount of content), I thought the easiest thing to is to is show everything in an overflowing container with a fixed height constraint. Within the next 24 hours (lol), I'll think through a potential Javascript interaction to show the currently playing event within the overflow. I hope this solution is okay!

Screen Shot 2020-07-21 at 6 27 58 PM

**Comment by lisasy** [comment]
# Overflowing container
Screen Shot 2020-07-22 at 2 05 05 PM

# Past + current states
Screen Shot 2020-07-22 at 1 59 46 PM

**Comment by joshpuetz** [comment]
This looks fantastic @lisasy! I'll get the merge conflict resolved and get it in!

**Pull request merged**
