### PR TITLE
Support 'outage' flag in schedule JSON

### PR DESCRIPTION
**Pull request by joshpuetz**
Adds support for the an `outage` flag in json:

```json
{
  "outage": true,
  "schedule":[
    {"id":1,...}
  ]
}
```

When `outage` is present and set to `true`, the `codeland-content` div will be hidden and the `codeland-outage` section displayed. Here's what it looks like right now:

codeland_-_DEV_local__Community_👩💻👨💻

@lisasy @jessleenyc Is there any wording we should put here? An image?

### CODE REVIEW

**Comment by fdoxyz** [comment]
@joshpuetz some ideas but not necessarily need to implement them:

Maybe something we can do when we show this is to create a single `setTimeout` for 15-30s that will reload the page for them? Does this make sense? As long as this doesn't conflict with the normal scheduled polling, the rabbit hole here would be an infinite loop of reloading.

Also an idea could be to leave the embedded YouTube link with a text that reads the note "We're experiencing technical difficulties, we'll be back shortly".

I think Gil can handle setting up the placeholder image for the stream that will say the same "Techinical difficulties, well be back shortly" so we could be safe to say the YouTube embed should be reliable

**Comment by joshpuetz** [comment]
@fdoxyz So when this gets loaded, the page is still polling for schedule data in 1 minute increments: if the `outage` flag is removed from the schedule json I have the page flip back to 'regular' mode. All of the schedule polling continues!

**Comment by lisasy** [comment]
@joshpuetz @fdoxyz @jessleenyc 

I think that a fallback experience we can have is to maintain this messaging, but maybe add the CodeLand logo + make the typography a little bit bigger and all. I can help assist that — if you want me to do that in *this* PR or a separate one after this gets merged, either works.

If people can't really do much here, would it be possible if we have some secondary message for them to explore the different Connect channels? Or would those also potentially be "out", as well?

**Comment by fdoxyz** [comment]
Great! The flow sounds good to me 👍🏼

**Comment by joshpuetz** [comment]
@lisasy Definitely feel free to contribute to this PR! I can handle merging them when we're done!

**Comment by joshpuetz** [comment]
Updated @lisasy!

**Comment by joshpuetz** [comment]
Closing this as attempting to resolve the conflict didn't go so well. Will open a different PR

**Pull request closed without merging**
